language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew check --stacktrace

after_success:
  - ./scripts/install-snapshot.sh

env:
  global:
    - secure: "gK+gJBrgA2yVj4EJYSSUp5mtIpgFDaHIzmA1bUa6OFYCZ5YcLEDf9lkIF0yDc5mkfV0zv6IIthklNO/DlElRscaKEUZBCbMwUB6kgikyyCrjxSr6mg9WxUA/GQQlIj0ADyXQHzBeox5U3HC3cOHFo4nqwk6A3W6iJyolbv4AJy4="
    - secure: "t4fgzcW1ws87dHtLCNNActocVQc1s1vP8EcW7coAn5gJyukyi3pZ8NyElE1Rb1pcO0/Jy4Jjax6YDJ5+uGUX+fpLlf4agBylSklY4zV+uU9DQGocgo0t/QVKUiVSHeWJWULvj8cCc8EG7s93vKYkS97AUnjgLntt0A+TN0oy9Jo="

sudo: false

cache:
  directories:
    - $HOME/.gradle
